name: Android APK (Debug)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components (33 ve 34 birlikte)
        run: |
          sdkmanager --install "platform-tools" \
                              "platforms;android-33" \
                              "platforms;android-34" \
                              "build-tools;33.0.2" \
                              "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Download Gradle 8.7
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH
          gradle -v

      - name: Build Debug APK (ayrıntılı log)
        run: gradle :app:assembleDebug --stacktrace --info --warning-mode all

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
